import { createHash } from "node:crypto";
import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { CONSENT_DIR, LICENCE_MIRROR_PATH, type LicenceAcceptance } from "@studio/shared";
import { resolveStoragePath } from "../storage.js";

/**
 * Files of the Personas registry, always under storage/consent/ (never served by /files, never in
 * error reports, denied to the Claude console):
 *
 *   consent/persons/<personId>/photos/<photoId>.<jpg|png|webp>
 *   consent/persons/<personId>/voice/<sampleId>.wav             (24 kHz mono, ≤ 30 s)
 *   consent/persons/<personId>/consents/<consentId>/evidence.<png|jpg|pdf>
 *   consent/archive/<personId>/                                 (after «Borrar persona»)
 *   consent/licences.json                                       (read-only mirror for the workers)
 *
 * Names are generated by the server; ids are nanoids (checked with SAFE_ID before use in a path).
 */

export const SAFE_ID = /^[A-Za-z0-9_-]{1,64}$/;

export const LIMITS = {
  photos: 10,
  photoBytes: 15 * 1024 * 1024,
  photoSide: 8192,
  voiceSamples: 5,
  voiceBytes: 25 * 1024 * 1024,
  voiceMinSec: 5,
  voiceMaxSec: 60,
  voiceKeepSec: 30,
  signatureBytes: 2 * 1024 * 1024,
  evidenceBytes: 20 * 1024 * 1024,
} as const;

export const personRel = (personId: string, ...parts: string[]) =>
  [CONSENT_DIR, "persons", personId, ...parts].join("/");
export const archiveRel = (personId: string) => [CONSENT_DIR, "archive", personId].join("/");

export function sha256(buf: Buffer | string): string {
  return createHash("sha256").update(buf).digest("hex");
}

export interface ImageInfo {
  type: "png" | "jpeg" | "webp";
  ext: "png" | "jpg" | "webp";
  mime: string;
  width: number;
  height: number;
}

/** Real type + size from the header bytes (PNG IHDR, JPEG SOFn, WebP VP8/VP8L/VP8X). */
export function sniffImage(buf: Buffer): ImageInfo | undefined {
  if (buf.length >= 24 && buf.readUInt32BE(0) === 0x89504e47 && buf.readUInt32BE(4) === 0x0d0a1a0a)
    return {
      type: "png",
      ext: "png",
      mime: "image/png",
      width: buf.readUInt32BE(16),
      height: buf.readUInt32BE(20),
    };
  if (buf.length >= 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let i = 2;
    while (i + 9 < buf.length) {
      if (buf[i] !== 0xff) {
        i++;
        continue;
      }
      const marker = buf[i + 1]!;
      if (marker === 0xd8 || (marker >= 0xd0 && marker <= 0xd7) || marker === 0x01) {
        i += 2;
        continue;
      }
      const len = buf.readUInt16BE(i + 2);
      const sof =
        marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
      if (sof)
        return {
          type: "jpeg",
          ext: "jpg",
          mime: "image/jpeg",
          height: buf.readUInt16BE(i + 5),
          width: buf.readUInt16BE(i + 7),
        };
      if (len < 2) return undefined;
      i += 2 + len;
    }
    return undefined;
  }
  if (
    buf.length >= 30 &&
    buf.toString("ascii", 0, 4) === "RIFF" &&
    buf.toString("ascii", 8, 12) === "WEBP"
  ) {
    const chunk = buf.toString("ascii", 12, 16);
    const base = { type: "webp" as const, ext: "webp" as const, mime: "image/webp" };
    if (chunk === "VP8 ")
      return {
        ...base,
        width: buf.readUInt16LE(26) & 0x3fff,
        height: buf.readUInt16LE(28) & 0x3fff,
      };
    if (chunk === "VP8L") {
      const b0 = buf[21]!;
      const b1 = buf[22]!;
      const b2 = buf[23]!;
      const b3 = buf[24]!;
      return {
        ...base,
        width: 1 + (((b1 & 0x3f) << 8) | b0),
        height: 1 + (((b3 & 0x0f) << 10) | (b2 << 2) | ((b1 & 0xc0) >> 6)),
      };
    }
    if (chunk === "VP8X")
      return { ...base, width: 1 + buf.readUIntLE(24, 3), height: 1 + buf.readUIntLE(27, 3) };
  }
  return undefined;
}

export const isPdf = (buf: Buffer) => buf.length >= 5 && buf.toString("ascii", 0, 5) === "%PDF-";

/** Write a buffer under storage (creates the folders). Returns the absolute path. */
export async function writeStorageFile(
  storageDir: string,
  rel: string,
  data: Buffer,
): Promise<string> {
  const abs = resolveStoragePath(storageDir, rel);
  await mkdir(path.dirname(abs), { recursive: true });
  await writeFile(abs, data);
  return abs;
}

export async function removeStorageFile(storageDir: string, rel: string): Promise<void> {
  await rm(resolveStoragePath(storageDir, rel), { force: true, recursive: true });
}

/**
 * «Borrar persona»: photos and voice samples are deleted; consents (with their evidence) move to
 * consent/archive/<id>/ (they prove what was authorized while the Person existed).
 */
export async function archivePersonFiles(storageDir: string, personId: string): Promise<void> {
  const dir = resolveStoragePath(storageDir, personRel(personId));
  await rm(path.join(dir, "photos"), { recursive: true, force: true });
  await rm(path.join(dir, "voice"), { recursive: true, force: true });
  const archive = resolveStoragePath(storageDir, archiveRel(personId));
  await mkdir(archive, { recursive: true });
  const consents = path.join(dir, "consents");
  await rename(consents, path.join(archive, `consents-${Date.now()}`)).catch(() => undefined);
  await rm(dir, { recursive: true, force: true });
}

/**
 * storage/consent/licences.json = {accepted: {[id]: {text_version, accepted_at}}} with the
 * accepted (not revoked) licences, written atomically (.tmp -> rename). The workers, models_cli
 * and doctor read it; only the api writes it.
 */
export async function writeLicenceMirror(
  storageDir: string,
  acceptances: readonly LicenceAcceptance[],
): Promise<void> {
  const accepted: Record<string, { text_version: string; accepted_at: string }> = {};
  for (const a of acceptances)
    if (!a.revoked_at)
      accepted[a.id] = { text_version: a.text_version, accepted_at: a.accepted_at };
  const abs = resolveStoragePath(storageDir, LICENCE_MIRROR_PATH);
  await mkdir(path.dirname(abs), { recursive: true });
  const tmp = `${abs}.tmp`;
  await writeFile(
    tmp,
    `${JSON.stringify({ accepted, updated_at: new Date().toISOString() }, null, 2)}\n`,
    "utf8",
  );
  await rename(tmp, abs);
}
