import { z } from "zod";
import { PublishSettingsSchema } from "./ai.js";
import { IdSchema, SecondsSchema, TimestampSchema } from "./common.js";
import { MotionSpecSchema } from "./motion.js";
import { CaptionStyleSchema, SubtitleSegmentSchema } from "./subtitles.js";
import { VoiceEffectSchema } from "./voice.js";

export const TrackKindSchema = z.enum(["video", "audio", "text", "motion"]);
export type TrackKind = z.infer<typeof TrackKindSchema>;

export const TransitionSchema = z.object({
  type: z.enum(["fade", "crossfade", "wipe", "slide", "zoom"]),
  durationSec: z.number().positive().max(10),
});
export type Transition = z.infer<typeof TransitionSchema>;

export const CropSchema = z.object({
  x: z.number().min(0),
  y: z.number().min(0),
  width: z.number().positive(),
  height: z.number().positive(),
});
export type Crop = z.infer<typeof CropSchema>;

/**
 * Picture-in-picture placement: anchor of the scaled clip inside the free canvas space
 * (0 = left/top edge, 0.5 = centered, 1 = right/bottom edge).
 */
export const ClipPositionSchema = z.object({
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
});
export type ClipPosition = z.infer<typeof ClipPositionSchema>;

export const TextStyleSchema = z.object({
  fontFamily: z.string().default("Inter"),
  fontSize: z.number().positive().default(64),
  color: z.string().default("#ffffff"),
  background: z.string().optional(),
  position: z.enum(["top", "center", "bottom"]).default("bottom"),
});
export type TextStyle = z.infer<typeof TextStyleSchema>;

/** A clip placed on a track. Times are in seconds. */
export const ClipSchema = z.object({
  id: IdSchema,
  trackId: IdSchema,
  /** Source media (video/audio/image tracks); absent for text/motion clips. */
  assetId: IdSchema.optional(),
  /** Position on the timeline. */
  start: SecondsSchema,
  /** Source in/out points (trim). duration on timeline = (out - in) / speed. */
  in: SecondsSchema.default(0),
  out: SecondsSchema,
  speed: z.number().min(0.1).max(16).default(1),
  volume: z.number().min(0).max(4).default(1),
  opacity: z.number().min(0).max(1).default(1),
  crop: CropSchema.optional(),
  /** PiP: size relative to the fitted full frame (1 = full frame). Absent = full frame. */
  scale: z.number().min(0.05).max(1).optional(),
  /** PiP: placement of the scaled clip (absent = centered). */
  position: ClipPositionSchema.optional(),
  transitionIn: TransitionSchema.optional(),
  transitionOut: TransitionSchema.optional(),
  /** Text track payload. */
  text: z.string().optional(),
  textStyle: TextStyleSchema.optional(),
  /** Motion track payload (rendered to renders/ by the motion engine). */
  motion: MotionSpecSchema.optional(),
  /** Rendered motion asset id once the motion job finished. */
  renderedAssetId: IdSchema.optional(),
  /** Audio effects chain applied on export. */
  voiceEffects: z.array(VoiceEffectSchema).default([]),
});
export type Clip = z.infer<typeof ClipSchema>;
export type ClipInput = z.input<typeof ClipSchema>;

export const TrackSchema = z.object({
  id: IdSchema,
  kind: TrackKindSchema,
  name: z.string(),
  muted: z.boolean().default(false),
  locked: z.boolean().default(false),
  hidden: z.boolean().default(false),
  clips: z.array(ClipSchema).default([]),
});
export type Track = z.infer<typeof TrackSchema>;

export const ProjectSettingsSchema = z.object({
  width: z.number().int().positive().default(1920),
  height: z.number().int().positive().default(1080),
  fps: z.number().positive().default(30),
  sampleRate: z.number().int().positive().default(48_000),
});
export type ProjectSettings = z.infer<typeof ProjectSettingsSchema>;

export const ProjectSchema = z.object({
  id: IdSchema,
  name: z.string().min(1),
  settings: ProjectSettingsSchema,
  tracks: z.array(TrackSchema).default([]),
  /** Subtitles generated by Whisper or typed manually. */
  subtitles: z.array(SubtitleSegmentSchema).default([]),
  /** Style used to burn/animate `subtitles` (absent = api default). */
  captionStyle: CaptionStyleSchema.optional(),
  /**
   * "Quemar subtítulos" chosen in the Export panel (absent = defaultBurnSubtitles). The preview
   * uses the same value so both show the same subtitles.
   */
  burnSubtitles: z.boolean().optional(),
  /** "Revisión para redes" + optional burned AI label (Sprint 1). */
  publish: PublishSettingsSchema.optional(),
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
});
export type Project = z.infer<typeof ProjectSchema>;

/** True when a visible motion track has an `animated-captions` clip (subtitles already on screen). */
export function hasAnimatedCaptions(project: Pick<Project, "tracks">): boolean {
  return project.tracks.some(
    (t) =>
      t.kind === "motion" &&
      !t.hidden &&
      t.clips.some((c) => c.motion?.template === "animated-captions"),
  );
}

/**
 * Default of ExportRequest.burnSubtitles: burn `project.subtitles` unless an animated-captions
 * clip already shows them (otherwise they appear twice).
 */
export function defaultBurnSubtitles(project: Pick<Project, "tracks">): boolean {
  return !hasAnimatedCaptions(project);
}

/** ExportRequest.burnSubtitles ?? Project.burnSubtitles ?? defaultBurnSubtitles(project). */
export function effectiveBurnSubtitles(
  project: Pick<Project, "tracks" | "burnSubtitles">,
  override?: boolean,
): boolean {
  return override ?? project.burnSubtitles ?? defaultBurnSubtitles(project);
}

export const CreateProjectSchema = z.object({
  name: z.string().min(1),
  settings: ProjectSettingsSchema.partial().optional(),
});
export type CreateProject = z.infer<typeof CreateProjectSchema>;
